# Unique identifier for the project
sonar.projectKey=ninja-reverse-proxy

# Project name displayed in SonarQube UI
sonar.projectName=Ninja Reverse Proxy

# Project version
sonar.projectVersion=1.0.0

# Path to the source directories
sonar.sources=src

# Path to the test files (if any)
sonar.tests=test.js

# Language specification
sonar.language=ts

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Exclude node_modules, dist, SSL certs, and configuration from analysis
sonar.exclusions=node_modules/**, dist/**, key.pem, cert.pem, config.yaml, Dockerfile, docker-compose.yml, Jenkinsfile
