apiVersion: v1
kind: Secret
metadata:
  name: ninja-proxy-tls
  namespace: reverse-proxy
  labels:
    app: ninja-reverse-proxy
type: Opaque
data:
  cert.pem: <BASE64_ENCODED_CERT>
  key.pem: <BASE64_ENCODED_KEY>
