global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ninja-reverse-proxy'
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['host.docker.internal:8443']
    tls_config:
      insecure_skip_verify: true
