apiVersion: apps/v1
kind: Deployment
metadata:
  name: ninja-reverse-proxy
  namespace: reverse-proxy
  labels:
    app: ninja-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ninja-reverse-proxy
  template:
    metadata:
      labels:
        app: ninja-reverse-proxy
    spec:
      containers:
        - name: proxy
          image: pravi2005/reverse-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: proxy-config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: proxy-tls
              mountPath: /app/cert.pem
              subPath: cert.pem
              readOnly: true
            - name: proxy-tls
              mountPath: /app/key.pem
              subPath: key.pem
              readOnly: true
          readinessProbe:
            httpGet:
              path: /__lb-stats
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /__lb-stats
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: proxy-config
          configMap:
            name: ninja-proxy-config
        - name: proxy-tls
          secret:
            secretName: ninja-proxy-tls
