apiVersion: v1
kind: Service
metadata:
  name: ninja-reverse-proxy-svc
  namespace: reverse-proxy
  labels:
    app: ninja-reverse-proxy
spec:
  selector:
    app: ninja-reverse-proxy
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
  type: ClusterIP
