apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ninja-proxy
  namespace: ninja-proxy
spec:
  selector:
    matchLabels:
      app: ninja-proxy
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
