global:
  scrape_interval: 15s
scrape_configs:
  - job_name: ninja-proxy
    static_configs:
      - targets: ['host.docker.internal:8443']
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /metrics
