apiVersion: v1
kind: Service
metadata:
  name: ninja-proxy
  namespace: ninja-proxy
spec:
  selector:
    app: ninja-proxy
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
