name: Security Scan
on:
  schedule:
    # Every Monday at 12:00 AM (Midnight) UTC.GitHub will check it weekly to ensure no new security vulnerabilities have been discovered in your dependencies.
    - cron: '0 0 * * 1'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - run: pnpm install --frozen-lockfile
      - run: pnpm audit
